---
title: "Analysis_features"
author: "Laura GREGOIRE"
date: "2023-11-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r package and path,  include=FALSE}
###packages
library("Publish")
library("car")
library("multcomp")
library("ggplot2")
library("lubridate")
library("stringr")
library("formattable")
library("ggpubr")
library("dplyr")
library("reshape2")

getwd()
setwd(dir = "C:/Users/2021lg003/Documents/LEASYSCAN_EXP_INDE_2023/RESULTS/3-AFTER_SMOOTHING/")
path="C:/Users/2021lg003/Documents/LEASYSCAN_EXP_INDE_2023/RESULTS/3-AFTER_SMOOTHING/"
```


```{r load data }
#We select data from September 27 to October 17. (We plot the weather data on these data).
#Then we remove the irrigation days

#Read and  reassemble the three periods. 
inputfile_TR<-read.csv("C:/Users/2021lg003/Documents/LEASYSCAN_ANALYSIS/2-DATA_SMOOTHING/results/OP-10_TR_smth.csv", sep = ";", header = TRUE)

colnames(inputfile_TR)[10:ncol(inputfile_TR)] <- sub("X","",colnames(inputfile_TR)[10:ncol(inputfile_TR)])
inputfile_TR=inputfile_TR[-c(8:9)]
timeline=colnames(inputfile_TR[8:ncol(inputfile_TR)])
timeline=dmy_hm(timeline)



##Liste genotypes -trt 
inputfile_TR$Geno_Trt<-str_c(inputfile_TR$Genotype, "_", inputfile_TR$Treatment) ##concatenate Geno et rep
geno_info<-data.frame(inputfile_TR$unit, inputfile_TR$Treatment, inputfile_TR$Genotype, inputfile_TR$Replicates, inputfile_TR$Geno_Trt)
colnames(geno_info)<-c("unit", "Treatment", "Genotype", "Replicates", "Geno_Trt")
geno_info=geno_info[-c(1:8),]
geno_info=na.omit(geno_info)



```

```{r VPD ETref plot}

climate_df<-inputfile_TR[-c(9:nrow(inputfile_TR)),] ###keep only climate rows (removed LC rows)
climate_df<-climate_df[,-c(2:7)] ###enlever les colonnes de 2 a 7
climate_df<-as.data.frame(t(climate_df))
colnames(climate_df)<-climate_df[1,]
climate_df<-climate_df[-1,]
rownames(climate_df)<- sub("X","",rownames(climate_df))
climate_df$Timestamp<-rownames(climate_df)
climate_df <- climate_df %>% mutate_at(c('Temp', 'RH','VPD', 'SR','WS', 'Tmax','Tmin', 'ETref'), as.numeric)
climate_df$Timestamp<-dmy_hm(climate_df$Timestamp)  
climate_df=na.omit(climate_df)


  png(file = "VPD_plot.png")
  ggplot(climate_df, aes(x=Timestamp, y=VPD))+
    geom_point() +
    labs(title = "VPD measured") + ylab("VPD (kPa)") + xlab("Date") +
    ggplot2::scale_x_datetime(labels = scales::date_format(format = "%d-%m"), date_breaks = "1 days")+
    theme(axis.text.x=element_text(angle = -45, hjust = 0))+
    geom_line()
  dev.off()
  while (!is.null(dev.list())) 
  
    png(file = "ETref_plot.png")
  ggplot(climate_df, aes(x=Timestamp, y=ETref))+
    geom_point() +
    labs(title = "ETref measured ") + ylab("ETref ((mm 15.min−1)") + xlab("Date") +
    ggplot2::scale_x_datetime(labels = scales::date_format(format = "%d-%m"), date_breaks = "1 days")+
    theme(axis.text.x=element_text(angle = -45, hjust = 0))+
    geom_line()
  dev.off()

```




```{r TRIAL PERIOD AND REMOVE IRRGATION DATES}
######### TR 
TR_profiles<-as.data.frame(t(inputfile_TR))
TR_profiles<-TR_profiles[-c(1:8)] ### remove climate data (first column)
TR_profiles<-TR_profiles[-c(1:2),] 
colnames(TR_profiles)=TR_profiles[nrow(TR_profiles),]
TR_profiles=TR_profiles[-nrow(TR_profiles),]
TR_profiles<-TR_profiles[-c(1:3),]
TR_profiles<-as.data.frame(TR_profiles)
TR_profiles<-TR_profiles[-c(1:2),]

TR_profiles$Timestamp<-rownames(TR_profiles)

TR_profiles$Timestamp<-dmy_hm(TR_profiles$Timestamp)



##identify duplicated column : 
geno_info$Geno_Trt[duplicated(geno_info$Geno_Trt)] ## Empty_WW_R4 and NA
geno_info[!duplicated(geno_info$Geno_Trt), ]

## remove duplicated column
TR_profiles <- TR_profiles[, !duplicated(colnames(TR_profiles))]

##only trial period
start=which(rownames(TR_profiles) == "28.09.2023.00.00") ##TEST !! CHANGE FOR REAL DATES ##careful with date format : periode 1 2023-10-01 00:00:00 and period 2 09.10.2023.23.45
end=which(rownames(TR_profiles) == "16.10.2023.23.45") ##change pour la fin de manip ! 
TR_trial_period=TR_profiles[start:end,] ###here, periode 2  middle of the experiment R_trial_period=TR_profiles
```



```{r TR TRIAL PERIOD}

##TR profil by plot 
for ( i in 1:ncol(TR_trial_period)) { 
  subset_geno_trt <- data.frame(TR_trial_period[i], rownames(TR_trial_period),colnames(TR_trial_period[i]))
  colnames(subset_geno_trt)=c("TR", "Timestamp","Geno_Trt")
  subset_geno_trt$Timestamp<-dmy_hm(subset_geno_trt$Timestamp)


  png(file = paste(path,"Transpiration rate Geno_Trt",subset_geno_trt$Geno_Trt[1],".png"))
  
  plot<-
    ggplot(data = subset_geno_trt, aes(subset_geno_trt$Timestamp,subset_geno_trt$TR))   +
    ylab("TR (mm m−2 15 min−1)")+
    xlab("Date ")+
    labs(title = subset_geno_trt$Geno_Trt[1])  +
    geom_point()+
    geom_line()   +
    ggplot2::scale_x_datetime(labels = scales::date_format(format = "%d-%m"), date_breaks = "1 days")+
    theme(axis.text.x=element_text(angle = -45, hjust = 0))
  
  print(plot)
  dev.off()
  print(i)

}

```


```{r TRIAL PERIOD AND REMOVE IRRGATION DATES}
##remove irrigation dates

 ##TEST CHANGE POUR LES VRAIES DATES D'IRRIGATION
start_irr_day=which(rownames(TR_trial_period) == "30.09.2023.00.00")
end_irr_day=which(rownames(TR_trial_period) == "30.09.2023.23.45")
TR_trial_period=TR_trial_period[-c(start_irr_day:end_irr_day),]


 ##TEST CHANGE POUR LES VRAIES DATES D'IRRIGATION
start_irr_day=which(rownames(TR_trial_period) == "01.10.2023.00.00")
end_irr_day=which(rownames(TR_trial_period) == "01.10.2023.23.45")
TR_trial_period=TR_trial_period[-c(start_irr_day:end_irr_day),]




 ##TEST CHANGE POUR LES VRAIES DATES D'IRRIGATION
start_irr_day=which(rownames(TR_trial_period) == "03.10.2023.00.00")
end_irr_day=which(rownames(TR_trial_period) == "03.10.2023.23.45")
TR_trial_period=TR_trial_period[-c(start_irr_day:end_irr_day),]




 ##TEST CHANGE POUR LES VRAIES DATES D'IRRIGATION
start_irr_day=which(rownames(TR_trial_period) == "06.10.2023.00.00")
end_irr_day=which(rownames(TR_trial_period) == "06.10.2023.23.45")
TR_trial_period=TR_trial_period[-c(start_irr_day:end_irr_day),]


#  ##TEST CHANGE POUR LES VRAIES DATES D'IRRIGATION
# start_irr_day=which(rownames(TR_trial_period) == "10.10.2023.00.00")
# end_irr_day=which(rownames(TR_trial_period) == "10.10.2023.23.45")
# TR_trial_period=TR_trial_period[-c(start_irr_day:end_irr_day),]

 ##TEST CHANGE POUR LES VRAIES DATES D'IRRIGATION
start_irr_day=which(rownames(TR_trial_period) == "13.10.2023.00.00")
end_irr_day=which(rownames(TR_trial_period) == "13.10.2023.23.45")
TR_trial_period=TR_trial_period[-c(start_irr_day:end_irr_day),]
```

```{r TR plot}
##test i=1
##change character to numeric
char_columns <- sapply(TR_trial_period, is.character)             # Identify character columns
data_chars_as_num <- TR_trial_period                              # Replicate data
data_chars_as_num[ , char_columns] <- as.data.frame(   # Recode characters as numeric
  apply(data_chars_as_num[ , char_columns], 2, as.numeric))
sapply(data_chars_as_num, class)  
TR_trial_period=data_chars_as_num


##TR profil by plot 
for ( i in 1:ncol(TR_trial_period)) { 
  subset_geno_trt <- data.frame(TR_trial_period[i], rownames(TR_trial_period),colnames(TR_trial_period[i]))
  colnames(subset_geno_trt)=c("TR", "Timestamp","Geno_Trt")
  subset_geno_trt$Timestamp<-dmy_hm(subset_geno_trt$Timestamp)


  png(file = paste(path,"Transpiration rate Geno_Trt",subset_geno_trt$Geno_Trt[1],".png"))
  
  plot<-
    ggplot(data = subset_geno_trt, aes(subset_geno_trt$Timestamp,subset_geno_trt$TR))   +
    ylab("TR (mm m−2 15 min−1)")+
    xlab("Date ")+
    labs(title = subset_geno_trt$Geno_Trt[1])  +
    geom_point()+
    geom_line()   +
    ggplot2::scale_x_datetime(labels = scales::date_format(format = "%d-%m"), date_breaks = "1 days")+
    theme(axis.text.x=element_text(angle = -45, hjust = 0))
  
  print(plot)
  dev.off()
  print(i)

}

g=geno_info$Genotype
g[1]
#select all columns that contain "genotype name" 
subset_geno=TR_trial_period[,c(  colnames(TR_trial_period)[grep(g[1],colnames(TR_trial_period))]
+ )]
subset_geno=cbind(subset_geno, rownames(subset_geno))
subset_geno$
subset_geno <- melt(subset_geno ,  id.vars = 'timeline', variable.name = 'rep')
subset_geno = cbind (subset_geno, timeline)

 # for (j in 1:nrow(subset_geno)) {
 #    if (isTRUE(subset_geno[j,3] > 1)){
 #  subset_geno[j,3]=NA
 #    }
 #    print(j)
 #    j=j+1
 #  }

x=subset_geno$timeline
y=subset_geno$value
##convert dataframe into plain text

 for ( i in levels(TR_profiles$genotype) ) { 

  
  
  png(file = paste("Transpiration rate Geno",i,".png"))

    
  png(file = paste("TR rate"i,"4_reps",".png"))
    
  plot<-
   ggplot(subset_geno, aes(x, y)) +
    geom_line(aes(colour = rep))+
    ylab("TR rate")+
    xlab("Date")+
    labs(title = paste("Transpiration Geno",i))  +
  geom_point(aes(color = rep))+
  ggplot2::scale_x_datetime(labels = scales::date_format(format = "%d-%m"), date_breaks = "1 days")+
  theme(axis.text.x=element_text(angle = -45, hjust = 0))

  print(plot)
  dev.off()
  
  print(i)

}


```

Do we have outlier in TR profils? 



```{r Load features smoothed data }
##### Load features smoothed data on trial period : 
##DO NOT LOAD IRRIGATION DATES
features_d1<-read.csv("C:/Users/2021lg003/Documents/LEASYSCAN_ANALYSIS/2-DATA_SMOOTHING/results/PERIODE1/smthTR_FeaturesTimeSeries/D.2023-09-28.csv", sep = ";")

features_d2<-read.csv("C:/Users/2021lg003/Documents/LEASYSCAN_ANALYSIS/2-DATA_SMOOTHING/results/PERIODE1/smthTR_FeaturesTimeSeries/D.2023-09-29.csv", sep = ";")

#features_d3<-read.csv("C:/Users/2021lg003/Documents/LEASYSCAN_ANALYSIS/2-DATA_SMOOTHING/results/PERIODE2/smthTR_FeaturesTimeSeries/D.2023-09-30.csv") 
#features_d4<-read.csv("./2-DATA_SMOOTHING/results/PERIODE2/smthTR_FeaturesTimeSeries/D.2023-10-01.csv") #
features_d5<-read.csv("C:/Users/2021lg003/Documents/LEASYSCAN_ANALYSIS/2-DATA_SMOOTHING/results/PERIODE2/smthTR_FeaturesTimeSeries/D.2023-10-02.csv") 
features_d6<-read.csv("C:/Users/2021lg003/Documents/LEASYSCAN_ANALYSIS/2-DATA_SMOOTHING/results/PERIODE2/smthTR_FeaturesTimeSeries/D.2023-10-03.csv") 
features_d7<-read.csv("C:/Users/2021lg003/Documents/LEASYSCAN_ANALYSIS/2-DATA_SMOOTHING/results/PERIODE2/smthTR_FeaturesTimeSeries/D.2023-10-04.csv") 
features_d8<-read.csv("C:/Users/2021lg003/Documents/LEASYSCAN_ANALYSIS/2-DATA_SMOOTHING/results/PERIODE2/smthTR_FeaturesTimeSeries/D.2023-10-05.csv") 
features_d9<-read.csv("C:/Users/2021lg003/Documents/LEASYSCAN_ANALYSIS/2-DATA_SMOOTHING/results/PERIODE2/smthTR_FeaturesTimeSeries/D.2023-10-06.csv") 
features_d10<-read.csv("C:/Users/2021lg003/Documents/LEASYSCAN_ANALYSIS/2-DATA_SMOOTHING/results/PERIODE2/smthTR_FeaturesTimeSeries/D.2023-10-07.csv") 
features_d11<-read.csv("C:/Users/2021lg003/Documents/LEASYSCAN_ANALYSIS/2-DATA_SMOOTHING/results/PERIODE2/smthTR_FeaturesTimeSeries/D.2023-10-08.csv") 
features_d12<-read.csv("C:/Users/2021lg003/Documents/LEASYSCAN_ANALYSIS/2-DATA_SMOOTHING/results/PERIODE2/smthTR_FeaturesTimeSeries/D.2023-10-09.csv") 
features_d13<-read.csv("C:/Users/2021lg003/Documents/LEASYSCAN_ANALYSIS/2-DATA_SMOOTHING/results/PERIODE2/smthTR_FeaturesTimeSeries/D.2023-10-10.csv") 
features_d14<-read.csv("C:/Users/2021lg003/Documents/LEASYSCAN_ANALYSIS/2-DATA_SMOOTHING/results/PERIODE3/smthTR_FeaturesTimeSeries/D.2023-10-11.csv") 
features_d15<-read.csv("C:/Users/2021lg003/Documents/LEASYSCAN_ANALYSIS/2-DATA_SMOOTHING/results/PERIODE3/smthTR_FeaturesTimeSeries/D.2023-10-12.csv") 
features_d16<-read.csv("C:/Users/2021lg003/Documents/LEASYSCAN_ANALYSIS/2-DATA_SMOOTHING/results/PERIODE3/smthTR_FeaturesTimeSeries/D.2023-10-13.csv") 
features_d17<-read.csv("C:/Users/2021lg003/Documents/LEASYSCAN_ANALYSIS/2-DATA_SMOOTHING/results/PERIODE3/smthTR_FeaturesTimeSeries/D.2023-10-14.csv") 
features_d18<-read.csv("C:/Users/2021lg003/Documents/LEASYSCAN_ANALYSIS/2-DATA_SMOOTHING/results/PERIODE3/smthTR_FeaturesTimeSeries/D.2023-10-15.csv") 
features_d19<-read.csv("C:/Users/2021lg003/Documents/LEASYSCAN_ANALYSIS/2-DATA_SMOOTHING/results/PERIODE3/smthTR_FeaturesTimeSeries/D.2023-10-16.csv") 


##rename maxET in MAXET BEFORE BINDING
library("dplyr")
#Using rename()
features_d1 <- features_d1 %>% 
       rename("MAXET" = "maxET")
features_d2 <- features_d2 %>% 
       rename("MAXET" = "maxET")




###ADD DATE ON EACH FEATURE BEFORE BINDING
colnames(features_d1)[8:ncol(features_d1)] <- paste(colnames(features_d1)[8:ncol(features_d1)], '_2023-09-28', sep='_')
colnames(features_d2)[8:ncol(features_d2)] <- paste(colnames(features_d2)[8:ncol(features_d2)], '_2023-09-29', sep='_')


features=cbind(features_d1,features_d2 )



features$Geno_Trt<-paste(features$Genotype, "|", features$Treatment)   
## KEEP ONE TIME : unit	old_unit	Treatment	Genotype	G..Alias	Replicates

MAXET=features[,grepl("MAXET",names(features))] ##probleme : on recupere les features maxET mais aussi slope.maxET,  slope.07.maxET, , curvmaxET .... :( Change before maxET to MAXET!

slope.seven.maxET=features[,grepl("slope.07.maxET",names(features))]         ##ok
slope.zero.seven = features[,grepl("slope.00.07",names(features))]             ##ok
slope.nineteen.midnight = features[,grepl("slope.19.23.45",names(features))] ##ok
curvmaxET = features[,grepl("curvmaxET",names(features))]                  ##ok    
total.auc = features[,grepl("total.auc",names(features))]                   ##ok
auc.ten.fifteen = features[,grepl("auc.10.15",names(features))]             ##ok
sd.ten.fifteen = features[,grepl("sd.10.15",names(features))]                  ##ok
auc.prop.ten.fifteen = features[,grepl("auc.prop.10.15",names(features))]    ##ok
auc.seven.nineteen = features[,grepl("auc.07.19",names(features))]           ##ok
sd.seven.nineteen = features[,grepl("sd.07.19",names(features))]              ##ok
auc.prop.seven.nineteen = features[,grepl("auc.prop.07.19",names(features))]   ##ok
auc.night= features[,grepl("auc.night",names(features))]                         ##ok
cos.sim.index= features[,grepl("cos.sim.index",names(features))]                 ##ok
```


```{r MaxET data }


###put feature on same column
maxET= cbind(maxET, features$Geno_Trt, features$Genotype, features$Treatment)

maxET <- melt(maxET ,  id.vars = "features$Geno_Trt", variable.name = 'rep')
maxET$value<-as.numeric(maxET$value)
maxET= na.omit(maxET)
colnames(maxET)=c( "Geno_Trt", "Date", "value")            
maxET = separate_wider_delim(maxET, cols = Geno_Trt, delim = "|", names = c("Geno", "Trt"))
colnames(maxET)=c("Genotype", "Treatment","Date", "maxET")
```


```{r anova maxET data }
model=lm(maxET~Genotype, data = maxET)
aov<-Anova(model)
print(aov)

#Response: value
#              Sum Sq   Df F value    Pr(>F)    
#Genotype  5.3670e+14  312  2.1303 < 2.2e-16 ***
#Residuals 9.5039e+14 1177                      
```


```{r H2 maxET }
H2=(aov$`Sum Sq`[1]/(aov$`Sum Sq`[1]+aov$`Sum Sq`[2]))
H2

```




```{r SLOPE_MAXET data }
# CREATE DATAFRAME FOR EACH FEATURE,ONE COLOMN PER DATE 
maxET = features[,grepl("MAXET", names(features))] 

###put feature on same column
maxET= cbind(maxET, features$Geno_Trt, features$Genotype, features$Treatment)

maxET <- melt(maxET ,  id.vars = "features$Geno_Trt", variable.name = 'rep')
maxET$value<-as.numeric(maxET$value)
maxET= na.omit(maxET)
colnames(maxET)=c( "Geno_Trt", "Date", "value")            
maxET = separate_wider_delim(maxET, cols = Geno_Trt, delim = "|", names = c("Geno", "Trt"))
colnames(maxET)=c("Genotype", "Treatment","Date", "maxET")
```


```{r anova maxET data }
model=lm(value~Genotype, data = maxET)
aov<-Anova(model)
print(aov)

#Response: value
#              Sum Sq   Df F value    Pr(>F)    
#Genotype  5.3670e+14  312  2.1303 < 2.2e-16 ***
#Residuals 9.5039e+14 1177                      
```


```{r H2 maxET }
H2=(aov$`Sum Sq`[1]/(aov$`Sum Sq`[1]+aov$`Sum Sq`[2]))
H2

```



```{r}
while (!is.null(dev.list()))  dev.off() ## si Error in dev.off() : 
 # impossible de fermer le p?riph?rique 1 (p?riph?rique null)
```
